replicaCount: 1
revisionHistoryLimit: 1

image:
  registry: asia.gcr.io/gcp-my-th-it-dev
  name: k8sdashboard
  tag: latest
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30

service:
  name: Node
  type: NodePort
  servicePort: 4654


ingress:
  enabled: false

  ## Kubernetes Dashboard Ingress annotations
  # annotations:
  #   kubernetes.io/ingress.class: nginx

  ## Kubernetes Dashboard Ingress hostnames
  # host: kubernetes-dashboard.domain.com

  ## Kubernetes Dashboard Ingress TLS configuration
  # tls:
  #   - secretName: kubernetes-dashboard-tls
  #     hosts:
  #       - kubernetes-dashboard.domain.com
